---
# tasks file for sa-vpn-softether

- name: SoftEther | Check vpnserver presence
  command: test -x {{softether_home}}/vpnserver
  ignore_errors: yes
  register: vpnserver_present
  tags:
      - softether


- name: SoftEther | Install package dependencies
  apt: pkg="{{item}}"
  with_items:
    - make
    - libssl-dev
  become: yes
  when: vpnserver_present | failed
  tags:
    - softether

- name: SoftEther | allow to reenter make process - reset folder
  file: path="{{softether_home}}" state="absent"
  become: yes
  when: vpnserver_present | failed
  tags:
    - softether

- name: SoftEther | Ensure target directory exists
  file: path="{{softether_home}}" state="directory"
  become: yes
  when: vpnserver_present | failed
  tags:
    - softether

- name: SoftEther | Ensure scenarios directory exists
  file: path="{{softether_home}}/scenarios" state="directory"
  become: yes
  when: vpnserver_present | failed
  tags:
    - softether

- name: SoftEther | Ensure scenarios directory exists
  file: path="{{softether_home}}/generated" state="directory"
  become: yes
  when: vpnserver_present | failed
  tags:
    - softether


- name: SoftEther | Download distribution
  get_url: url="http://www.softether-download.com/files/softether/v4.20-9608-rtm-2016.04.17-tree/Linux/SoftEther_VPN_Server/64bit_-_Intel_x64_or_AMD64/softether-vpnserver-v4.20-9608-rtm-2016.04.17-linux-x64-64bit.tar.gz" dest="/tmp/softether.tar.gz"
  become: yes
  tags:
    - softether


- name: SoftEther | unarchive
#  shell: "tar -xzf /tmp/softether.tar.gz -C {{softether_home}}"
  unarchive: src="/tmp/softether.tar.gz" dest="{{softether_location}}" remote_src=yes
  when: vpnserver_present | failed
  become: yes
  tags:
    - softether

- name: SoftEther | make
  shell: yes 1 | make
  when: vpnserver_present | failed
  args:
    chdir: "{{softether_home}}"
  tags:
    - softether


- name: SoftEther | configure lang.config
  lineinfile:  dest="{{softether_home}}/lang.config" regexp=^(en|ja|cn)$  line={{ softether_lang }} create=yes
  become: yes
  tags:
    - softether

- name: SoftEther | install init script
  template: src="{{role_dir}}/templates/startup/vpnserver.init.j2"  dest=/etc/init.d/vpnserver  mode=0755
  when: upstart_system == "upstart"
  become: yes
  tags:
    - softether

- name: SoftEther | install init script
  template: src="{{role_dir}}/templates/startup/vpnserver.service.j2"  dest=/etc/systemd/system/vpnserver.service  mode=0755
  when: upstart_system == "systemd"
  become: yes
  tags:
    - softether

- name: SoftEther | Reset configuration (1/5)
  service: name="vpnserver" enabled=yes  state=stopped
  become: yes
  tags:
    - softether

- name: SoftEther | Reset configuration (2/5)
  file: path="{{softether_home}}/vpn_server.config" state="absent"
  become: yes
  tags:
    - softether

- name: SoftEther | Keys in sysctl.conf (3/5)
  sysctl: name={{item.name}} value={{item.value}} ignoreerrors=yes state={{item.state | default('present')}}
  with_items: "{{ softether_sysctl_conf_lines | default()}}"
  become: yes
  tags:
    - softether

- name: SoftEther | Reset configuration (4/5)
  shell: sysctl --system
  become: yes
  tags:
    - softether

- name: SoftEther | Reset configuration (5/5)
  service: name="vpnserver" enabled=yes  state=started
  become: yes
  tags:
    - softether


- name: SoftEther | Template unattended setup (builtin)
  template: src="{{role_dir}}/templates/scenarios/{{item}}" dest="{{softether_home}}/scenarios/{{item}}"
  with_items:
    - create_hub
    - check
  become: yes
  tags:
    - softether

- name: SoftEther | Check configuration
  shell: ./vpncmd localhost /tools /IN:scenarios/check
  args:
    chdir: "{{softether_home}}"
  become: yes
  tags:
    - softether

- name: SoftEther | Proceed with setup
  shell: ./vpncmd localhost /server /IN:{{softether_init_script}}
  args:
    chdir: "{{softether_home}}"
  become: yes
  tags:
    - softether

- name: SoftEther | Restart service
  service: name="vpnserver" enabled=yes  state=started
  become: yes
  tags:
    - softether


- debug: msg="Copy artifacts as scp {{ansible_ssh_user | default('youruser')}}@{{ansible_ssh_host | default('yourhost')}}:{{softether_home}}/generated/* ."
